import React from 'react';
export let jsonData = {
    data: [
      {
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
          value: 100,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 1000,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'burner',
        limit: 100,
        status: 'active',
        expiry: '9 feb',
        icon :"./burn.png",
      },
      {
        name: "Quickbooks'",
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
          value: 50,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 250,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'subscription',
        limit: 10,
        status: 'active',
        icon :"./connect.png",
      },
      {
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
          value: 100,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 1000,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'burner',
        limit: 100,
        status: 'active',
        expiry: '9 feb',
        icon :"./burn.png",
      },
      {
        name: "Quickbooks'",
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
          value: 50,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 250,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'subscription',
        limit: 10,
        status: 'active',
        icon :"./connect.png",
      },{
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
          value: 100,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 1000,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'burner',
        limit: 100,
        status: 'active',
        expiry: '9 feb',
        icon :"./burn.png",
      },
      {
        name: "Quickbooks'",
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
          value: 50,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 250,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'subscription',
        limit: 10,
        status: 'active',
        icon :"./connect.png",
      },{
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
          value: 100,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 1000,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'burner',
        limit: 100,
        status: 'active',
        expiry: '9 feb',
        icon :"./burn.png",
      },
      {
        name: "Quickbooks'",
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
          value: 50,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 250,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'subscription',
        limit: 10,
        status: 'active',
        icon :"./connect.png",
      },{
        name: 'Mixmax',
        budget_name: 'Software subscription',
        owner_id: 1,
        spent: {
          value: 100,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 1000,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'burner',
        limit: 100,
        status: 'active',
        expiry: '9 feb',
        icon :"./burn.png",
      },
      {
        name: "Quickbooks'",
        budget_name: 'Software subscription',
        owner_id: 2,
        spent: {
          value: 50,
          currency: 'SGD',
        },
        available_to_spend: {
          value: 250,
          currency: 'SGD',
        },
        frequency:'Monthly',
        card_type: 'subscription',
        limit: 10,
        status: 'active',
        icon :"./connect.png",
      },
      
    ],
    page: 1,
    per_page: 10,
    total: 100,
  };

